#!/usr/bin/env python
"""Django's command-line utility for administrative tasks."""
import os
import sys
def main():
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'LibraryBookSearch.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)
if __name__ == '__main__':
    main()
from django.contrib import admin
from django.apps import AppConfig
class UserConfig(AppConfig):
    name = 'User'
from django.db import models
from django.urls import path
from User import views
urlpatterns=[
    path('',views.index),
    path('Users',views.userlogin),
    path('register',views.register),
    path('RegAction',views.RegAction),
    path('LogAction',views.LogAction),
    path('userhome',views.userhome),
    path('Profile',views.Profile),
    path('SearchByTitle',views.SearchByTitle),
    path('SearchTitleAction',views.SearchTitleAction),
    path('SearchByAuthor',views.SearchByAuthor),
    path('SearchAuthorAction',views.SearchAuthorAction),
    path('SearchByYear',views.SearchByYear),
    path('SearchYearAction',views.SearchYearAction),
	]
    """LibraryBookSearch URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include
import AdminApp
import User
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('User.urls')),
    path('adminapp/',include('AdminApp.urls')),
]
"""
Django settings for LibraryBookSearch project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR=os.path.join(BASE_DIR,'Templates')
STATIC_DIR=os.path.join(BASE_DIR,'Static')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%w7$01p+mpp(r0d!13iu-7_crok02oaf&^bkzb5id&za6-yx*p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'User',
    'AdminApp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryBookSearch.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryBookSearch.wsgi.application'
"""
WSGI config for LibraryBookSearch project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/howto/deployment/wsgi/
"""

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'LibraryBookSearch.settings')

application = get_wsgi_application()



# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[
    STATIC_DIR
    ]
from django.shortcuts import render
import pymysql
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import linear_model
import os
import datetime

# Create your views here.
def index(request):
  return render(request,'User/index.html')

def userlogin(request):
  return render(request,'User/Users.html')
def register(request):
  return render(request,'User/Register.html')
def userhome(request):
  return render(request,'User/UserHome.html')
def RegAction(request):
  name=request.POST['name']
  email=request.POST['email']
  mobile=request.POST['mobile']
  address=request.POST['address']
  username=request.POST['username']
  password=request.POST['password']

  con=pymysql.connect(host="localhost",user="root",password="root",database="lsb")
  cur=con.cursor()
  i=cur.execute("insert into user values(null,'"+name+"','"+email+"','"+mobile+"','"+address+"','"+username+"','"+password+"')")
  con.commit()
  con.close()
  cur.close()
  if i>0:
    context={'data':'Registration Successful...!!'}
    return render(request,'User/Register.html',context)
  else:
    context={'data','Registration Failed...!!'}
    return render(request,'User/Register.html',context)
def LogAction(request):
  username=request.POST.get('username')
  password=request.POST.get('password')
  con=pymysql.connect(host="localhost",user="root",password="root",database="lsb")
  cur=con.cursor()
  cur.execute("select *  from user where username='"+username+"'and password='"+password+"'")
  data=cur.fetchone()
  if data is not None:
    request.session['user']=username
    request.session['userid']=data[0]
    return render(request,'User/UserHome.html')
  else:
    context={'data':'Login Failed ....!!'}
    return render(request,'User/Users.html',context)

  
def Profile(request):
  uid=str(request.session['userid'])
  con=pymysql.connect(host="localhost",user="root",password="root",database="lsb")
  cur=con.cursor()
  cur.execute("select * from user where id='"+uid+"'")
  data=cur.fetchall()
  strdata="<table border='1'><tr><th>Name</th><th>Email</th><th>Mobile</th><th>Address</th></tr>"
  for i in data:
    strdata+="<tr><td>"+str(i[2])+"</td><td>"+str(i[3])+"</td><td>"+str(i[4])+"</td><td>"+str(i[4])+"</td></tr>"
  context={'data':strdata}
  return render(request,'User/ViewProfile.html',context)
def SearchByTitle(request):
  return render(request,'User/SearchByTitle.html')
def SearchTitleAction(request):
  title=request.POST.get('title')
  con=pymysql.connect(host="localhost",user="root",password="root",database="lsb")
  cur=con.cursor()
  cur.execute("select * from books where bookname like'%"+title+"%'")
  data=cur.fetchall()
  strdata="<table border='1'><tr style='color:red;background:skyblue;height:60px;text-align:center;'><th>Book Name</th><th>Author</th><th>Publication Here</th><th>Book Genre</th><th>Description</th></tr>"
  for i in data:
    strdata+="<tr><td>"+str(i[1])+"</td><td>"+str(i[2])+"</td><td>"+str(i[3])+"</td><td>"+str(i[4])+"</td><td>"+str(i[5])+"</td></tr>"
  context={'data':strdata}
  return render(request,'User/ViewSearchTAction.html',context)
def SearchByAuthor(request):
  return render(request,'User/SearchByAuthor.html')
def SearchAuthorAction(request):
  title=request.POST.get('author')
  con=pymysql.connect(host="localhost",user="root",password="root",database="lsb")
  cur=con.cursor()
  cur.execute("select * from books where author like'%"+title+"%'")
  data=cur.fetchall()
  strdata="<table border='1'><tr style='color:red;background:skyblue;height:60px;text-align:center;'><th>Book Name</th><th>Author</th><th>Publication Here</th><th>Book Genre</th><th>Description</th></tr>"
  for i in data:
    strdata+="<tr><td>"+str(i[1])+"</td><td>"+str(i[2])+"</td><td>"+str(i[3])+"</td><td>"+str(i[4])+"</td><td>"+str(i[5])+"</td></tr>"
  context={'data':strdata}
  return render(request,'User/ViewSearchTAction.html',context)
def SearchByYear(request):
  return render(request,'User/SearchByYear.html')
def SearchYearAction(request):
  title=request.POST.get('year')
  con=pymysql.connect(host="localhost",user="root",password="root",database="lsb")
  cur=con.cursor()
  cur.execute("select * from books where pyear like'%"+title+"%'")
  data=cur.fetchall()
  strdata="<table border='1'><tr style='color:red;background:skyblue;height:60px;text-align:center;'><th>Book Name</th><th>Author</th><th>Publication Here</th><th>Book Genre</th><th>Description</th></tr>"
  for i in data:
    strdata+="<tr><td>"+str(i[1])+"</td><td>"+str(i[2])+"</td><td>"+str(i[3])+"</td><td>"+str(i[4])+"</td><td>"+str(i[5])+"</td></tr>"
  context={'data':strdata}
  return render(request,'User/ViewSearchTAction.html',context)
  

